Repository saqib-devops/Online-Payment-Servive-UK, pull requests merged in 2023-04, with the labels that each got.

#1 Register moddule ==>> register ,signup,login added
  register/admin.py
  register/forms.py
  register/models.py
  register/templates/register/login.html
  register/templates/register/logout.html
  register/templates/register/signup.html
  register/urls.py
  register/views.py
  requirements.txt
  webapps2023/settings.py
Labels: enhancement

#4 Errorss Resolved
  .gitignore
  payapp/models.py
  payapp/views.py
  register/urls.py
  templates/register/login.html
  templates/register/logout.html
  templates/register/signup.html
  webapps2023/settings.py
Labels: bug

#6 Dashboard , Send Transaction , and Request transaction Templates Added
  payapp/urls.py
  payapp/views.py
  register/models.py
  register/views.py
  templates/navbar.html
  templates/payapp/dashboard.html
  templates/payapp/request_transaction_create.html
  templates/payapp/request_transaction_list.html
  templates/payapp/transaction_create.html
  templates/payapp/transactions.html
  webapps2023/settings.py
Labels: bug

#5 UPDT ♻️ new changes in models api and tests --migrations required
  payapp/models.py
  payapp/tests.py
  payapp/urls.py
  payapp/utils.py
  payapp/views.py
  register/models.py
  register/tests.py
  register/urls.py
  requirements.txt
  templates/register/login.html
  webapps2023/settings.py
  webapps2023/urls.py
Labels: bug, enhancement

#7 UPDT: transactions and transactions-requests updates added
  payapp/urls.py
  payapp/views.py
  register/tests.py
Labels: bug

#14 All Test Cases Created and tested Successfullly
  README.md
  payapp/test.py
  payapp/tests.py
  payapp/views.py
  register/models.py
  register/test.py
  register/tests.py
  webapps2023/settings.py
Labels: documentation
